package personality;

/**
 *
 * @author Quinn Clayburn
 */

import javax.swing.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.List;

public class PersonalityQuizGUI extends javax.swing.JFrame {

    /**
     * Creates new form PersonalityQuizGUI
     */

    private PersonalityQuiz quiz;
    private int currentQuestionIndex = 0;
    private List<PersonalityAnswer> answers = new ArrayList<>();


    public PersonalityQuizGUI() {
        initComponents();

        quiz = new PersonalityQuiz();

        if (!quiz.getQuestions().isEmpty()) {
            //getQuestion(quiz.getQuestions().get(0));
            quiz.getQuestions().get(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        titleLabel = new javax.swing.JLabel();
        questionLabel = new javax.swing.JLabel();
        choice1Button = new javax.swing.JRadioButton();
        choice2Button = new javax.swing.JRadioButton();
        choice3Button = new javax.swing.JRadioButton();
        nextButton = new javax.swing.JButton();



        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Are you an introvert or an extrovert?");

        questionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        questionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionLabel.setText("Select a choice and click next to start.");

        buttonGroup1.add(choice1Button);
        choice1Button.setText("Choice 1");
        choice1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choice1ButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(choice2Button);
        choice2Button.setText("Choice 2");

        buttonGroup1.add(choice3Button);
        choice3Button.setText("Choice 3");

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(36, Short.MAX_VALUE)
                                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(133, 133, 133)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(choice2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(choice1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(choice3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(142, 142, 142)
                                                .addComponent(nextButton)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(titleLabel)
                                .addGap(26, 26, 26)
                                .addComponent(questionLabel)
                                .addGap(18, 18, 18)
                                .addComponent(choice1Button)
                                .addGap(18, 18, 18)
                                .addComponent(choice2Button)
                                .addGap(18, 18, 18)
                                .addComponent(choice3Button)
                                .addGap(18, 18, 18)
                                .addComponent(nextButton)
                                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (currentQuestionIndex < quiz.getQuestions().size()) {
            PersonalityQuestion question = quiz.getQuestions().get(currentQuestionIndex);
            int selected = -1;

            if (choice1Button.isSelected()) selected = 0;
            else if (choice2Button.isSelected()) selected = 1;
            else if (choice3Button.isSelected()) selected = 2;

            if (selected == -1) {
                JOptionPane.showMessageDialog(this, "Please select an option.");
                return;
            }

            answers.add(new PersonalityAnswer(question, selected));
            currentQuestionIndex++;

            if (currentQuestionIndex < quiz.getQuestions().size()) {
                displayQuestion(quiz.getQuestions().get(currentQuestionIndex));
            }
            else {
                showResults();
            }

        }

    }

    private void choice1ButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void displayQuestion(PersonalityQuestion question) {
        questionLabel.setText(question.getQuestionText());
        choice1Button.setText(question.getChoices()[0]);
        choice2Button.setText(question.getChoices()[1]);
        choice3Button.setText(question.getChoices()[2]);
        buttonGroup1.clearSelection();
    }

    private void showResults() {
        int introvertPoints = 0;
        int extrovertPoints = 0;

        for (PersonalityAnswer answer : answers) {
            int points = answer.getSelectedPoints();
            if (points < 0) introvertPoints += Math.abs(points);
            else extrovertPoints += points;
        }

        PersonalityCompute compute = new PersonalityCompute(introvertPoints, extrovertPoints);
        JOptionPane.showMessageDialog(this, compute.getResult());
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalityQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalityQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalityQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalityQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonalityQuizGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton choice1Button;
    private javax.swing.JRadioButton choice2Button;
    private javax.swing.JRadioButton choice3Button;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration
}
